name: Pre-commit

on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master

jobs:
  pre_commit:
    name: Run pre-commit
    runs-on: ubuntu-latest
    steps:
      - uses: Alfresco/alfresco-build-tools/.github/actions/pre-commit@v8.28.1
